-- ============================================================================
-- Baker's Fresh — catalog seed from website_manifest.csv
-- Ensures categories exist, replaces all cakes, uses local public paths for
-- image_url until you run: npm run upload:catalog-storage
-- ============================================================================

BEGIN;

INSERT INTO categories (slug, name, description, display_order) VALUES
  ('birthday', 'Birthday Cakes', 'Make every birthday memorable', 1),
  ('anniversary', 'Anniversary Cakes', 'Celebrate love with sweet moments', 2),
  ('wedding', 'Wedding Cakes', 'Premium tiered cakes for your big day', 3),
  ('photo-cake', 'Photo Cakes', 'Edible photos printed on cream', 4),
  ('designer', 'Designer & Custom', 'Bring your wildest cake ideas to life', 5),
  ('kids', 'Kids Cakes', 'Cartoon characters and fun themes', 6),
  ('eggless', 'Eggless Cakes', 'Pure vegetarian, equally delicious', 7),
  ('pastries', 'Pastries', 'Single-serve treats, freshly made daily', 8)
ON CONFLICT (slug) DO NOTHING;

DELETE FROM cakes;

INSERT INTO cakes (slug, category_id, name, description, image_url, base_price_inr, flavors, sizes_available, is_eggless, is_featured, display_order) VALUES
  (
    'anniversary-chocolate-curl-hearts-001',
    (SELECT id FROM categories WHERE slug = 'anniversary'),
    'Chocolate Curl Hearts',
    'from our kitchen. Chocolate Curl Hearts. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/anniversary-chocolate-curl-hearts-001.jpg',
    999,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    true,
    1
  ),
  (
    'anniversary-red-rose-silhouette-couple-002',
    (SELECT id FROM categories WHERE slug = 'anniversary'),
    'Red Rose Silhouette Couple',
    'from our kitchen. Red Rose Silhouette Couple. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/anniversary-red-rose-silhouette-couple-002.jpg',
    999,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    true,
    2
  ),
  (
    'anniversary-calendar-heart-toppers-003',
    (SELECT id FROM categories WHERE slug = 'anniversary'),
    'Calendar Heart Toppers',
    'from our kitchen. Calendar Heart Toppers. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/anniversary-calendar-heart-toppers-003.jpg',
    999,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    true,
    3
  ),
  (
    'anniversary-teal-white-floral-brush-004',
    (SELECT id FROM categories WHERE slug = 'anniversary'),
    'Teal White Floral Brush',
    'from our kitchen. Teal White Floral Brush. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/anniversary-teal-white-floral-brush-004.jpg',
    999,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    true,
    4
  ),
  (
    'anniversary-pink-white-floral-3tier-005',
    (SELECT id FROM categories WHERE slug = 'anniversary'),
    'Pink White Floral 3Tier',
    'from our kitchen. Pink White Floral 3Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/anniversary-pink-white-floral-3tier-005.jpg',
    999,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    true,
    5
  ),
  (
    'birthday-white-sprinkles-vanilla-001',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'White Sprinkles Vanilla',
    'from our kitchen. White Sprinkles Vanilla. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-white-sprinkles-vanilla-001.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    true,
    6
  ),
  (
    'birthday-chocolate-ferrero-drip-002',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Ferrero Drip',
    'from our kitchen. Chocolate Ferrero Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-ferrero-drip-002.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    true,
    7
  ),
  (
    'birthday-chocolate-cone-overload-priya-003',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Cone Overload Priya',
    'from our kitchen. Chocolate Cone Overload Priya. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-cone-overload-priya-003.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    true,
    8
  ),
  (
    'birthday-pink-rose-drip-rosette-004',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Pink Rose Drip Rosette',
    'from our kitchen. Pink Rose Drip Rosette. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-pink-rose-drip-rosette-004.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    9
  ),
  (
    'birthday-chocolate-kitkat-curls-005',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Kitkat Curls',
    'from our kitchen. Chocolate Kitkat Curls. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-kitkat-curls-005.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    10
  ),
  (
    'birthday-red-ruffle-cone-tier-006',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Red Ruffle Cone Tier',
    'from our kitchen. Red Ruffle Cone Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-red-ruffle-cone-tier-006.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    11
  ),
  (
    'birthday-gold-chocolate-cherry-007',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Gold Chocolate Cherry',
    'from our kitchen. Gold Chocolate Cherry. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-gold-chocolate-cherry-007.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    12
  ),
  (
    'birthday-white-cone-chocolate-drip-008',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'White Cone Chocolate Drip',
    'from our kitchen. White Cone Chocolate Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-white-cone-chocolate-drip-008.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    13
  ),
  (
    'birthday-blue-hot-air-balloon-5-009',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Blue Hot Air Balloon 5',
    'from our kitchen. Blue Hot Air Balloon 5. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-blue-hot-air-balloon-5-009.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    14
  ),
  (
    'birthday-fitness-themed-weights-010',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Fitness Themed Weights',
    'from our kitchen. Fitness Themed Weights. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-fitness-themed-weights-010.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    15
  ),
  (
    'birthday-strawberry-7th-birthday-011',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Strawberry 7Th Birthday',
    'from our kitchen. Strawberry 7Th Birthday. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-strawberry-7th-birthday-011.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    16
  ),
  (
    'birthday-yellow-white-drip-gold-012',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Yellow White Drip Gold',
    'from our kitchen. Yellow White Drip Gold. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-yellow-white-drip-gold-012.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    17
  ),
  (
    'birthday-ocean-underwater-theme-013',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Ocean Underwater Theme',
    'from our kitchen. Ocean Underwater Theme. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-ocean-underwater-theme-013.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    18
  ),
  (
    'birthday-chocolate-heart-drip-2tier-014',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Heart Drip 2Tier',
    'from our kitchen. Chocolate Heart Drip 2Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-heart-drip-2tier-014.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    19
  ),
  (
    'birthday-gender-reveal-he-or-she-015',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Gender Reveal He Or She',
    'from our kitchen. Gender Reveal He Or She. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-gender-reveal-he-or-she-015.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    20
  ),
  (
    'birthday-chocolate-gold-foil-drip-016',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Gold Foil Drip',
    'from our kitchen. Chocolate Gold Foil Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-gold-foil-drip-016.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    21
  ),
  (
    'birthday-colorful-drip-balloon-topper-017',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Colorful Drip Balloon Topper',
    'from our kitchen. Colorful Drip Balloon Topper. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-colorful-drip-balloon-topper-017.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    22
  ),
  (
    'birthday-pink-white-pearl-balloons-018',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Pink White Pearl Balloons',
    'from our kitchen. Pink White Pearl Balloons. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-pink-white-pearl-balloons-018.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    23
  ),
  (
    'birthday-mac-makeup-pink-birthday-019',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Mac Makeup Pink Birthday',
    'from our kitchen. Mac Makeup Pink Birthday. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-mac-makeup-pink-birthday-019.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    24
  ),
  (
    'birthday-mothers-day-pink-chocolate-020',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Mothers Day Pink Chocolate',
    'from our kitchen. Mothers Day Pink Chocolate. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-mothers-day-pink-chocolate-020.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    25
  ),
  (
    'birthday-pink-floral-three-tier-elegant-021',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Pink Floral Three Tier Elegant',
    'from our kitchen. Pink Floral Three Tier Elegant. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-pink-floral-three-tier-elegant-021.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    26
  ),
  (
    'birthday-pink-white-peony-three-tier-022',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Pink White Peony Three Tier',
    'from our kitchen. Pink White Peony Three Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-pink-white-peony-three-tier-022.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    27
  ),
  (
    'birthday-pokemon-pikachu-yellow-spikes-023',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Pokemon Pikachu Yellow Spikes',
    'from our kitchen. Pokemon Pikachu Yellow Spikes. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-pokemon-pikachu-yellow-spikes-023.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    28
  ),
  (
    'birthday-yellow-crown-tall-elegant-024',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Yellow Crown Tall Elegant',
    'from our kitchen. Yellow Crown Tall Elegant. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-yellow-crown-tall-elegant-024.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    29
  ),
  (
    'birthday-yellow-black-spiral-candles-025',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Yellow Black Spiral Candles',
    'from our kitchen. Yellow Black Spiral Candles. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-yellow-black-spiral-candles-025.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    30
  ),
  (
    'birthday-mint-white-chocolate-drip-026',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Mint White Chocolate Drip',
    'from our kitchen. Mint White Chocolate Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-mint-white-chocolate-drip-026.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    31
  ),
  (
    'birthday-rainbow-butterscotch-sitanshu-027',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Rainbow Butterscotch Sitanshu',
    'from our kitchen. Rainbow Butterscotch Sitanshu. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-rainbow-butterscotch-sitanshu-027.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    32
  ),
  (
    'birthday-chocolate-colorful-candy-028',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Colorful Candy',
    'from our kitchen. Chocolate Colorful Candy. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-colorful-candy-028.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    33
  ),
  (
    'birthday-chocolate-candy-gems-029',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Candy Gems',
    'from our kitchen. Chocolate Candy Gems. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-candy-gems-029.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    34
  ),
  (
    'birthday-gold-star-first-birthday-030',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Gold Star First Birthday',
    'from our kitchen. Gold Star First Birthday. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-gold-star-first-birthday-030.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    35
  ),
  (
    'birthday-yellow-monster-cake-031',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Yellow Monster Cake',
    'from our kitchen. Yellow Monster Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-yellow-monster-cake-031.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    36
  ),
  (
    'birthday-black-white-multicolor-cake-032',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Black White Multicolor Cake',
    'from our kitchen. Black White Multicolor Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-black-white-multicolor-cake-032.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    37
  ),
  (
    'birthday-black-chocolate-sprinkle-033',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Black Chocolate Sprinkle',
    'from our kitchen. Black Chocolate Sprinkle. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-black-chocolate-sprinkle-033.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    38
  ),
  (
    'birthday-chocolate-velvet-drip-034',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Velvet Drip',
    'from our kitchen. Chocolate Velvet Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-velvet-drip-034.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    39
  ),
  (
    'birthday-chocolate-gemstone-cake-035',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Gemstone Cake',
    'from our kitchen. Chocolate Gemstone Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-gemstone-cake-035.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    40
  ),
  (
    'birthday-chocolate-brown-shards-036',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Brown Shards',
    'from our kitchen. Chocolate Brown Shards. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-brown-shards-036.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    41
  ),
  (
    'birthday-brown-white-swirl-pattern-037',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Brown White Swirl Pattern',
    'from our kitchen. Brown White Swirl Pattern. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-brown-white-swirl-pattern-037.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    42
  ),
  (
    'birthday-butterscotch-glory-black-orange-038',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Butterscotch Glory Black Orange',
    'from our kitchen. Butterscotch Glory Black Orange. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-butterscotch-glory-black-orange-038.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    43
  ),
  (
    'birthday-pineapple-bliss-yellow-orange-039',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Pineapple Bliss Yellow Orange',
    'from our kitchen. Pineapple Bliss Yellow Orange. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-pineapple-bliss-yellow-orange-039.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    44
  ),
  (
    'birthday-pink-geometric-quilted-party-040',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Pink Geometric Quilted Party',
    'from our kitchen. Pink Geometric Quilted Party. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-pink-geometric-quilted-party-040.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    45
  ),
  (
    'birthday-black-gold-rose-drip-041',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Black Gold Rose Drip',
    'from our kitchen. Black Gold Rose Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-black-gold-rose-drip-041.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    46
  ),
  (
    'birthday-chocolate-claw-birthday-042',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Chocolate Claw Birthday',
    'from our kitchen. Chocolate Claw Birthday. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-chocolate-claw-birthday-042.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    47
  ),
  (
    'birthday-white-rosette-confetti-043',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'White Rosette Confetti',
    'from our kitchen. White Rosette Confetti. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-white-rosette-confetti-043.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    48
  ),
  (
    'birthday-pink-drip-balloon-044',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'Pink Drip Balloon',
    'from our kitchen. Pink Drip Balloon. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-pink-drip-balloon-044.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    49
  ),
  (
    'birthday-white-drip-name-045',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'White Drip Name',
    'from our kitchen. White Drip Name. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-white-drip-name-045.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    50
  ),
  (
    'birthday-white-floral-cupcake-set-046',
    (SELECT id FROM categories WHERE slug = 'birthday'),
    'White Floral Cupcake Set',
    'from our kitchen. White Floral Cupcake Set. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/birthday-white-floral-cupcake-set-046.jpg',
    699,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    51
  ),
  (
    'cupcakes-oreo-brownie-pairs-001',
    (SELECT id FROM categories WHERE slug = 'pastries'),
    'Oreo Brownie Pairs',
    'from our kitchen. Oreo Brownie Pairs. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/cupcakes-oreo-brownie-pairs-001.jpg',
    189,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    52
  ),
  (
    'kids-theme-minecraft-7th-birthday-001',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Minecraft 7Th Birthday',
    'from our kitchen. Minecraft 7Th Birthday. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-minecraft-7th-birthday-001.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    53
  ),
  (
    'kids-theme-gym-fitness-dumbbell-blue-002',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Gym Fitness Dumbbell Blue',
    'from our kitchen. Gym Fitness Dumbbell Blue. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-gym-fitness-dumbbell-blue-002.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    54
  ),
  (
    'kids-theme-frozen-elsa-anna-olaf-003',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Frozen Elsa Anna Olaf',
    'from our kitchen. Frozen Elsa Anna Olaf. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-frozen-elsa-anna-olaf-003.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    55
  ),
  (
    'kids-theme-rainbow-candyland-stars-004',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Rainbow Candyland Stars',
    'from our kitchen. Rainbow Candyland Stars. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-rainbow-candyland-stars-004.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    56
  ),
  (
    'kids-theme-avengers-superhero-divyan-005',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Avengers Superhero Divyan',
    'from our kitchen. Avengers Superhero Divyan. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-avengers-superhero-divyan-005.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    57
  ),
  (
    'kids-theme-barbie-pink-dress-doll-006',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Barbie Pink Dress Doll',
    'from our kitchen. Barbie Pink Dress Doll. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-barbie-pink-dress-doll-006.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    58
  ),
  (
    'kids-theme-blue-balloon-priam-5-007',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Blue Balloon Priam 5',
    'from our kitchen. Blue Balloon Priam 5. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-blue-balloon-priam-5-007.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    59
  ),
  (
    'kids-theme-camping-adventure-2tier-008',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Camping Adventure 2Tier',
    'from our kitchen. Camping Adventure 2Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-camping-adventure-2tier-008.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    60
  ),
  (
    'kids-theme-pink-princess-girl-topper-009',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Pink Princess Girl Topper',
    'from our kitchen. Pink Princess Girl Topper. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-pink-princess-girl-topper-009.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    61
  ),
  (
    'kids-theme-rainbow-unicorn-colorful-010',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Rainbow Unicorn Colorful',
    'from our kitchen. Rainbow Unicorn Colorful. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-rainbow-unicorn-colorful-010.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    62
  ),
  (
    'kids-theme-unicorn-rainbow-face-011',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Unicorn Rainbow Face',
    'from our kitchen. Unicorn Rainbow Face. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-unicorn-rainbow-face-011.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    63
  ),
  (
    'kids-theme-giraffe-safari-yellow-012',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Giraffe Safari Yellow',
    'from our kitchen. Giraffe Safari Yellow. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-giraffe-safari-yellow-012.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    64
  ),
  (
    'kids-theme-ocean-sea-creatures-2-013',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Ocean Sea Creatures 2',
    'from our kitchen. Ocean Sea Creatures 2. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-ocean-sea-creatures-2-013.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    65
  ),
  (
    'kids-theme-giraffe-spotted-yellow-014',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Giraffe Spotted Yellow',
    'from our kitchen. Giraffe Spotted Yellow. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-giraffe-spotted-yellow-014.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    66
  ),
  (
    'kids-theme-anime-fire-character-2tier-015',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Anime Fire Character 2Tier',
    'from our kitchen. Anime Fire Character 2Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-anime-fire-character-2tier-015.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    67
  ),
  (
    'kids-theme-bee-honeycomb-yellow-pink-016',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Bee Honeycomb Yellow Pink',
    'from our kitchen. Bee Honeycomb Yellow Pink. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-bee-honeycomb-yellow-pink-016.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    68
  ),
  (
    'kids-theme-construction-yellow-hat-2tier-017',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Construction Yellow Hat 2Tier',
    'from our kitchen. Construction Yellow Hat 2Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-construction-yellow-hat-2tier-017.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    69
  ),
  (
    'kids-theme-cat-figures-turquoise-pink-018',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Cat Figures Turquoise Pink',
    'from our kitchen. Cat Figures Turquoise Pink. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-cat-figures-turquoise-pink-018.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    70
  ),
  (
    'kids-theme-peppa-pig-rainbow-drip-019',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Peppa Pig Rainbow Drip',
    'from our kitchen. Peppa Pig Rainbow Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-peppa-pig-rainbow-drip-019.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    71
  ),
  (
    'kids-theme-influencer-girl-social-media-020',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Influencer Girl Social Media',
    'from our kitchen. Influencer Girl Social Media. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-influencer-girl-social-media-020.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    72
  ),
  (
    'kids-theme-hot-air-balloon-teddy-bear-021',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Hot Air Balloon Teddy Bear',
    'from our kitchen. Hot Air Balloon Teddy Bear. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-hot-air-balloon-teddy-bear-021.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    73
  ),
  (
    'kids-theme-cocomelon-rainbow-4th-birthday-022',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Cocomelon Rainbow 4Th Birthday',
    'from our kitchen. Cocomelon Rainbow 4Th Birthday. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-cocomelon-rainbow-4th-birthday-022.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    74
  ),
  (
    'kids-theme-minnie-mouse-red-rosette-023',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Minnie Mouse Red Rosette',
    'from our kitchen. Minnie Mouse Red Rosette. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-minnie-mouse-red-rosette-023.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    75
  ),
  (
    'kids-theme-barbie-doll-pink-yellow-rainbow-024',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Barbie Doll Pink Yellow Rainbow',
    'from our kitchen. Barbie Doll Pink Yellow Rainbow. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-barbie-doll-pink-yellow-rainbow-024.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    76
  ),
  (
    'kids-theme-barbie-princess-cake-025',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Barbie Princess Cake',
    'from our kitchen. Barbie Princess Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-barbie-princess-cake-025.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    77
  ),
  (
    'kids-theme-creamsoda-character-birthday-026',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Creamsoda Character Birthday',
    'from our kitchen. Creamsoda Character Birthday. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-creamsoda-character-birthday-026.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    78
  ),
  (
    'kids-theme-shin-chan-4th-birthday-multi-tier-027',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Shin Chan 4Th Birthday Multi Tier',
    'from our kitchen. Shin Chan 4Th Birthday Multi Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-shin-chan-4th-birthday-multi-tier-027.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    79
  ),
  (
    'kids-theme-chocolate-panda-bear-028',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Chocolate Panda Bear',
    'from our kitchen. Chocolate Panda Bear. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-chocolate-panda-bear-028.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    80
  ),
  (
    'kids-theme-unicorn-rainbow-029',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Unicorn Rainbow',
    'from our kitchen. Unicorn Rainbow. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-unicorn-rainbow-029.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    81
  ),
  (
    'kids-theme-boss-baby-first-030',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Boss Baby First',
    'from our kitchen. Boss Baby First. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-boss-baby-first-030.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    82
  ),
  (
    'kids-theme-superman-blue-tier-031',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Superman Blue Tier',
    'from our kitchen. Superman Blue Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-superman-blue-tier-031.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    83
  ),
  (
    'kids-theme-barbie-pink-doll-032',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Barbie Pink Doll',
    'from our kitchen. Barbie Pink Doll. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-barbie-pink-doll-032.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    84
  ),
  (
    'kids-theme-bear-polka-dot-blue-033',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Bear Polka Dot Blue',
    'from our kitchen. Bear Polka Dot Blue. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-bear-polka-dot-blue-033.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    85
  ),
  (
    'kids-theme-bear-heart-pink-first-034',
    (SELECT id FROM categories WHERE slug = 'kids'),
    'Bear Heart Pink First',
    'from our kitchen. Bear Heart Pink First. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/kids-theme-bear-heart-pink-first-034.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    86
  ),
  (
    'others-designer-fashion-bags-tier-001',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Designer Fashion Bags Tier',
    'from our kitchen. Designer Fashion Bags Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-designer-fashion-bags-tier-001.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    87
  ),
  (
    'others-mini-caramel-cheesecake-002',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Mini Caramel Cheesecake',
    'from our kitchen. Mini Caramel Cheesecake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-mini-caramel-cheesecake-002.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    88
  ),
  (
    'others-designer-akku-luxury-bags-003',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Designer Akku Luxury Bags',
    'from our kitchen. Designer Akku Luxury Bags. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-designer-akku-luxury-bags-003.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    89
  ),
  (
    'others-silver-rose-geode-tier-004',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Silver Rose Geode Tier',
    'from our kitchen. Silver Rose Geode Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-silver-rose-geode-tier-004.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    90
  ),
  (
    'others-blue-buttercream-floral-005',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Blue Buttercream Floral',
    'from our kitchen. Blue Buttercream Floral. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-blue-buttercream-floral-005.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    91
  ),
  (
    'others-black-gold-drip-tier-006',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Black Gold Drip Tier',
    'from our kitchen. Black Gold Drip Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-black-gold-drip-tier-006.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    92
  ),
  (
    'others-quit-smoking-novelty-007',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Quit Smoking Novelty',
    'from our kitchen. Quit Smoking Novelty. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-quit-smoking-novelty-007.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    93
  ),
  (
    'others-pastel-mint-pink-drip-008',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Pastel Mint Pink Drip',
    'from our kitchen. Pastel Mint Pink Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-pastel-mint-pink-drip-008.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    94
  ),
  (
    'others-mother-newborn-figurine-009',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Mother Newborn Figurine',
    'from our kitchen. Mother Newborn Figurine. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-mother-newborn-figurine-009.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    95
  ),
  (
    'others-orange-glazed-lotus-010',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Orange Glazed Lotus',
    'from our kitchen. Orange Glazed Lotus. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-orange-glazed-lotus-010.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    96
  ),
  (
    'others-turquoise-rose-spiral-2tier-011',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Turquoise Rose Spiral 2Tier',
    'from our kitchen. Turquoise Rose Spiral 2Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-turquoise-rose-spiral-2tier-011.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    97
  ),
  (
    'others-vodka-bottle-luxury-noir-012',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Vodka Bottle Luxury Noir',
    'from our kitchen. Vodka Bottle Luxury Noir. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-vodka-bottle-luxury-noir-012.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    98
  ),
  (
    'others-gold-silver-foil-rose-3tier-013',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Gold Silver Foil Rose 3Tier',
    'from our kitchen. Gold Silver Foil Rose 3Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-gold-silver-foil-rose-3tier-013.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    99
  ),
  (
    'others-gold-white-rose-luxury-3tier-014',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Gold White Rose Luxury 3Tier',
    'from our kitchen. Gold White Rose Luxury 3Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-gold-white-rose-luxury-3tier-014.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    100
  ),
  (
    'others-golden-crown-rose-3tier-015',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Golden Crown Rose 3Tier',
    'from our kitchen. Golden Crown Rose 3Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-golden-crown-rose-3tier-015.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    101
  ),
  (
    'others-chocolate-whiskey-beer-drip-016',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Chocolate Whiskey Beer Drip',
    'from our kitchen. Chocolate Whiskey Beer Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-chocolate-whiskey-beer-drip-016.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    102
  ),
  (
    'others-geode-blue-green-designer-017',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Geode Blue Green Designer',
    'from our kitchen. Geode Blue Green Designer. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-geode-blue-green-designer-017.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    103
  ),
  (
    'others-geode-green-blue-mirror-018',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Geode Green Blue Mirror',
    'from our kitchen. Geode Green Blue Mirror. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-geode-green-blue-mirror-018.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    104
  ),
  (
    'others-blue-geode-mirror-glaze-019',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Blue Geode Mirror Glaze',
    'from our kitchen. Blue Geode Mirror Glaze. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-blue-geode-mirror-glaze-019.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    105
  ),
  (
    'others-yellow-ice-cream-cone-drip-020',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Yellow Ice Cream Cone Drip',
    'from our kitchen. Yellow Ice Cream Cone Drip. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-yellow-ice-cream-cone-drip-020.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    106
  ),
  (
    'others-pubg-themed-cake-021',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Pubg Themed Cake',
    'from our kitchen. Pubg Themed Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-pubg-themed-cake-021.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    107
  ),
  (
    'others-modern-geode-cake-022',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Modern Geode Cake',
    'from our kitchen. Modern Geode Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-modern-geode-cake-022.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    108
  ),
  (
    'others-luxury-metallic-geodes-023',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Luxury Metallic Geodes',
    'from our kitchen. Luxury Metallic Geodes. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-luxury-metallic-geodes-023.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    109
  ),
  (
    'others-luxury-metallic-geodes-024',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Luxury Metallic Geodes',
    'from our kitchen. Luxury Metallic Geodes. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-luxury-metallic-geodes-024.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    110
  ),
  (
    'others-kitkat-wrap-chocolate-candy-025',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Kitkat Wrap Chocolate Candy',
    'from our kitchen. Kitkat Wrap Chocolate Candy. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-kitkat-wrap-chocolate-candy-025.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    111
  ),
  (
    'others-chocolate-white-swirl-modern-026',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Chocolate White Swirl Modern',
    'from our kitchen. Chocolate White Swirl Modern. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-chocolate-white-swirl-modern-026.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    112
  ),
  (
    'others-ice-cream-cone-chocolate-027',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Ice Cream Cone Chocolate',
    'from our kitchen. Ice Cream Cone Chocolate. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-ice-cream-cone-chocolate-027.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    113
  ),
  (
    'others-red-velvet-rose-product-slice-028',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Red Velvet Rose Product Slice',
    'from our kitchen. Red Velvet Rose Product Slice. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-red-velvet-rose-product-slice-028.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    114
  ),
  (
    'others-multicolor-panel-designer-029',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Multicolor Panel Designer',
    'from our kitchen. Multicolor Panel Designer. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-multicolor-panel-designer-029.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    115
  ),
  (
    'others-red-hijab-figure-030',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Red Hijab Figure',
    'from our kitchen. Red Hijab Figure. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-red-hijab-figure-030.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    116
  ),
  (
    'others-red-hijab-figure-variant-031',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Red Hijab Figure Variant',
    'from our kitchen. Red Hijab Figure Variant. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-red-hijab-figure-variant-031.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    117
  ),
  (
    'others-red-hijab-figure-alt-032',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Red Hijab Figure Alt',
    'from our kitchen. Red Hijab Figure Alt. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-red-hijab-figure-alt-032.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    118
  ),
  (
    'others-feather-rock-designer-033',
    (SELECT id FROM categories WHERE slug = 'designer'),
    'Feather Rock Designer',
    'from our kitchen. Feather Rock Designer. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/others-feather-rock-designer-033.jpg',
    1299,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    119
  ),
  (
    'pastries-red-velvet-pastry-slice-001',
    (SELECT id FROM categories WHERE slug = 'pastries'),
    'Red Velvet Pastry Slice',
    'from our kitchen. Red Velvet Pastry Slice. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/pastries-red-velvet-pastry-slice-001.jpg',
    189,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    120
  ),
  (
    'pastries-pistachio-cream-pastry-002',
    (SELECT id FROM categories WHERE slug = 'pastries'),
    'Pistachio Cream Pastry',
    'from our kitchen. Pistachio Cream Pastry. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/pastries-pistachio-cream-pastry-002.jpg',
    189,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    121
  ),
  (
    'pastries-almond-mango-cream-pastry-003',
    (SELECT id FROM categories WHERE slug = 'pastries'),
    'Almond Mango Cream Pastry',
    'from our kitchen. Almond Mango Cream Pastry. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/pastries-almond-mango-cream-pastry-003.jpg',
    189,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    122
  ),
  (
    'pastries-lotus-biscoff-mini-cheesecake-004',
    (SELECT id FROM categories WHERE slug = 'pastries'),
    'Lotus Biscoff Mini Cheesecake',
    'from our kitchen. Lotus Biscoff Mini Cheesecake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/pastries-lotus-biscoff-mini-cheesecake-004.jpg',
    189,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    123
  ),
  (
    'pastries-mocha-cream-cake-slice-005',
    (SELECT id FROM categories WHERE slug = 'pastries'),
    'Mocha Cream Cake Slice',
    'from our kitchen. Mocha Cream Cake Slice. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/pastries-mocha-cream-cake-slice-005.jpg',
    189,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    124
  ),
  (
    'pastries-chocolate-cheesecake-slice-006',
    (SELECT id FROM categories WHERE slug = 'pastries'),
    'Chocolate Cheesecake Slice',
    'from our kitchen. Chocolate Cheesecake Slice. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/pastries-chocolate-cheesecake-slice-006.jpg',
    189,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    125
  ),
  (
    'photo-print-teal-white-portrait-cake-001',
    (SELECT id FROM categories WHERE slug = 'photo-cake'),
    'Teal White Portrait Cake',
    'from our kitchen. Teal White Portrait Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/photo-print-teal-white-portrait-cake-001.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    126
  ),
  (
    'photo-print-fathers-day-photo-cake-002',
    (SELECT id FROM categories WHERE slug = 'photo-cake'),
    'Fathers Day Photo Cake',
    'from our kitchen. Fathers Day Photo Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/photo-print-fathers-day-photo-cake-002.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    127
  ),
  (
    'photo-print-chocolate-ribbon-photo-face-003',
    (SELECT id FROM categories WHERE slug = 'photo-cake'),
    'Chocolate Ribbon Photo Face',
    'from our kitchen. Chocolate Ribbon Photo Face. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/photo-print-chocolate-ribbon-photo-face-003.jpg',
    899,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    128
  ),
  (
    'wedding-pink-rosette-couple-tier-001',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'Pink Rosette Couple Tier',
    'from our kitchen. Pink Rosette Couple Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-pink-rosette-couple-tier-001.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    129
  ),
  (
    'wedding-pink-butterfly-three-tier-002',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'Pink Butterfly Three Tier',
    'from our kitchen. Pink Butterfly Three Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-pink-butterfly-three-tier-002.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    130
  ),
  (
    'wedding-white-pink-bride-groom-003',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'White Pink Bride Groom',
    'from our kitchen. White Pink Bride Groom. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-white-pink-bride-groom-003.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    131
  ),
  (
    'wedding-gold-pink-gradient-rings-004',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'Gold Pink Gradient Rings',
    'from our kitchen. Gold Pink Gradient Rings. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-gold-pink-gradient-rings-004.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    132
  ),
  (
    'wedding-blush-pink-rose-white-3tier-005',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'Blush Pink Rose White 3Tier',
    'from our kitchen. Blush Pink Rose White 3Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-blush-pink-rose-white-3tier-005.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    133
  ),
  (
    'wedding-crown-gold-floral-2tier-006',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'Crown Gold Floral 2Tier',
    'from our kitchen. Crown Gold Floral 2Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-crown-gold-floral-2tier-006.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    134
  ),
  (
    'wedding-white-pearl-engaged-two-tier-007',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'White Pearl Engaged Two Tier',
    'from our kitchen. White Pearl Engaged Two Tier. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-white-pearl-engaged-two-tier-007.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    135
  ),
  (
    'wedding-turquoise-pillared-cake-008',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'Turquoise Pillared Cake',
    'from our kitchen. Turquoise Pillared Cake. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-turquoise-pillared-cake-008.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    136
  ),
  (
    'wedding-turquoise-blue-roses-formal-009',
    (SELECT id FROM categories WHERE slug = 'wedding'),
    'Turquoise Blue Roses Formal',
    'from our kitchen. Turquoise Blue Roses Formal. order a custom version in your flavour and size.',
    '/instagram_imported_bakers_fresh/wedding-turquoise-blue-roses-formal-009.jpg',
    2499,
    ARRAY['chocolate','vanilla','custom'],
    ARRAY['0.5kg','1kg','1.5kg','2kg'],
    false,
    false,
    137
  );

COMMIT;
